import{i as a,S as f}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function u(o,s,t){o.innerHTML="";const n=s.hits.map(e=>`<li class="gallery-item">
                    <a class="gallery-link" href="${e.largeImageURL}">
                        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
                    </a>
                    <ul class="info">
                        <li class="info-list">Likes: <span>${e.likes}</span></li>
                        <li class="info-list">Views: <span>${e.views}</span></li>
                        <li class="info-list">Comments: <span>${e.comments}</span></li>
                        <li class="info-list">Downloads: <span>${e.downloads}</span></li>
                    </ul>
                </li>`);o.innerHTML=n.join(""),t.refresh()}const m="43829547-150c89c88df8cf7a92100352d",d="https://pixabay.com/api/",y=o=>{const s=new URLSearchParams({q:o,key:m,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${d}?${s}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()})},p=document.querySelector(".form"),g=document.querySelector('input[name="text"]'),l=document.querySelector(".gallery"),c=document.querySelector(".loader");p.addEventListener("submit",o=>{o.preventDefault();const s=g.value.trim();s?(c.style.display="block",l.innerHTML="",y(s).then(t=>{t.hits.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}):u(l,t,h)}).catch(t=>{console.log(t),a.error({message:"Sorry, there was an error processing your request.",position:"center"})}).finally(()=>{c.style.display="none",o.target.reset()})):(o.target.reset(),a.error({message:"Please enter the data.",position:"center"}),l.innerHTML="")});const h=new f(".gallery a",{captionsData:"alt",captionDelay:200});
//# sourceMappingURL=commonHelpers.js.map
